project_id = "gjlrxikynlbpsvrpwebp"

[functions.credit-welcome-bonus]
verify_jwt = true

[functions.admin-pin-management]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.process-banner-image]
verify_jwt = true

[functions.admin-users]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.check-email-blocked]
verify_jwt = false

[functions.auto-story-generator]
verify_jwt = false

[functions.remove-background]
verify_jwt = true
