project_id = "gjlrxikynlbpsvrpwebp"

[functions.credit-welcome-bonus]
verify_jwt = false

[functions.admin-pin-management]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.process-banner-image]
verify_jwt = true

[functions.admin-users]
verify_jwt = false
